<?php

namespace FondOfSpryker\Shared\Newsletter;

interface NewsletterConstants
{
    public const ROUTE_NEWSLETTER_FOOTER = 'ROUTE_NEWSLETTER_FOOTER';
    public const ROUTE_NEWSLETTER_SUBMIT_FORM = 'ROUTE_NEWSLETTER_SUBMIT_FORM';
    public const ROUTE_NEWSLETTER_CONFIRM_SUBSCRIPTION = 'ROUTE_NEWSLETTER_CONFIRM_SUBSCRIPTION';
    public const ROUTE_NEWSLETTER_UNSUBSCRIBE = 'ROUTE_NEWSLETTER_UNSUBSCRIBE';

    public const NEWSLETTER_LOCALIZED_CONFIGS = 'NEWSLETTER_LOCALIZED_CONFIGS';

    public const NEWSLETTER_CONFIRMATION_PATH = 'NEWSLETTER_CONFIRMATION_PATH';
    public const NEWSLETTER_ALREADY_SUBSCRIBED_PATH = 'NEWSLETTER_ALREADY_SUBSCRIBED_PATH';

    // ROUTE_NEWSLETTER_SUBSCRIBE
    public const ROUTE_NEWSLETTER_SUBSCRIBE_SUCCESS = 'ROUTE_NEWSLETTER_SUBSCRIBE_SUCCESS';
    public const ROUTE_NEWSLETTER_ALREADY_SUBSCRIBED = 'ROUTE_NEWSLETTER_ALREADY_SUBSCRIBED';
    public const ROUTE_NEWSLETTER_FAILURE = 'ROUTE_NEWSLETTER_FAILURE';

}
